version: '3.4'

services:
  app:
    command: [ "python", "main.py", "--device", "0" ]
    environment:
      PYTHONUNBUFFERED: 1
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    # Edit here
    devices:
      # - "/dev/video0:/dev/video0"
      # - "/dev/video1:/dev/video0"
      - "/dev/video2:/dev/video0"
    build:
      context: .
